dataset:
  name: "document_anomaly"
  format: "folder"
  path: "/path/to/your/dataset"
  normal_dir: "train/good"
  abnormal_dir: "test/abnormal"
  normal_test_dir: "test/good"
  task: "segmentation"  # or "classification" if you don't need pixel-wise predictions

model:
  name: "patchcore"
  backbone: "wide_resnet50_2"
  pre_trained: true

preprocessing:
  resize:
    height: 640
    width: 640
    p: 1.0

optimization:
  num_epochs: 1
  batch_size: 32

metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC

visualization:
  show_images: False
  save_images: True

project:
  path: "./results"
  log_images_to: []

export:
  format: "onnx"  # You can choose "onnx" or "openvino"
  output: "./exported_model"
